spring:
  datasource:
    url: jdbc:mysql://localhost:8889/library?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

jwt:
  secret: librarySecretKey
  expirationMs: 86400000

business:
  uploadsDir: /Users/jordan/OPC_Projet7 copie/uploads
  loanPeriod: 4
